apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: odoo
  labels:
    app: odoo
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: odoo
    tier: postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo
  labels:
    app: odoo
spec:
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 32000
  selector:
    app: odoo
    tier: frontend
  type: NodePort